INSERT INTO USERS(ID, NAME, PASSWORD, TWITTERID, ENABLED) VALUES('007', 'admin', 'password', '@admin', 1);
INSERT INTO USERS(ID, NAME, PASSWORD, TWITTERID, ENABLED) VALUES('001', 'user', 'password', '@user', 1);

INSERT INTO USER_ROLES(ID, USERID, AUTHORITY) VALUES('100007','007','ROLE_ADMIN');
INSERT INTO USER_ROLES(ID, USERID, AUTHORITY) VALUES('100001','001','ROLE_USER');
