CREATE TABLE USERS (ID VARCHAR, NAME VARCHAR, PASSWORD VARCHAR, TWITTERID VARCHAR, ENABLED TINYINT, PRIMARY KEY (ID))
CREATE TABLE LINK (ID VARCHAR, URL VARCHAR, DESCRIPTION VARCHAR, BOARDID VARCHAR, NAME VARCHAR, PRIMARY KEY (ID))
CREATE TABLE BOARD (ID VARCHAR, NAME VARCHAR, DESCRIPTION VARCHAR, USERID VARCHAR, PRIMARY KEY (ID))
CREATE TABLE USER_ROLES (ID VARCHAR, USERID VARCHAR, AUTHORITY VARCHAR)
