CREATE TABLE USERS (ID VARCHAR, NAME VARCHAR, PASSWORD VARCHAR, TWITTERID VARCHAR, PRIMARY KEY (ID))
CREATE TABLE LINK (ID VARCHAR, URL VARCHAR, DESCRIPTION VARCHAR, BOARDID VARCHAR, PRIMARY KEY (ID))
CREATE TABLE BOARD (ID VARCHAR, NAME VARCHAR, DESCRIPTION VARCHAR, USERID VARCHAR, PRIMARY KEY (ID))